apiVersion: v1
kind: Pod
metadata:
  name: app-dynamic-cds-volume
  namespace: default
spec:
  containers:
    - image: hub.baidubce.com/jpaas-public/nginx:latest
      imagePullPolicy: Always
      name: nginx
      volumeMounts:
        - name: cds-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: cds-volume
      persistentVolumeClaim:
        claimName: pvc-dynamic-cds-volume