apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cds-hp1-with-secret
parameters:
  paymentTiming: Postpaid
  reservationLength: "3"
  storageType: hp1
  csi.storage.k8s.io/provisioner-secret-name: "cds-access-key"
  csi.storage.k8s.io/provisioner-secret-namespace: "default"
  csi.storage.k8s.io/controller-publish-secret-name: "cds-access-key"
  csi.storage.k8s.io/controller-publish-secret-namespace: "default"
provisioner: cds.csi.baidubce.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer