apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bos-bucket
  namespace: "default"
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  csi:
    driver: "bos.csi.baidubce.com"
    volumeHandle: <Your BOS bucket>
    nodePublishSecretRef:
      name: "bos-access-key"
      namespace: "default"
  mountOptions:
    - "-o meta_expires=0"
  persistentVolumeReclaimPolicy: Retain