apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cds-block-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: cds-hp1-with-secret
  volumeMode: Block