# Default values for cds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  provisioner: registry.baidubce.com/cce-plugin-pro/csi-provisioner:v1.6.1
  attacher: registry.baidubce.com/cce-plugin-pro/csi-attacher:v2.2.1
  resizer: registry.baidubce.com/cce-plugin-pro/csi-resizer:v1.2.0
  registrar: registry.baidubce.com/cce-plugin-pro/csi-node-driver-registrar:v2.1.0
  plugin: registry.baidubce.com/cce-plugin-pro/cce-csi-plugin:v1.1.0

endpoint:
  bcc: bcc.gz.baidubce.com
  cds: bcc.gz.baidubce.com
  cceGateway:


driverName: cds.csi.baidubce.com
clusterID:
region:
topologyMode: meta
authMode: key
maxVolumesPerNode: 10
logLevel: 5
kubeletDataDirPath: /home/cce/kubelet

nodeServerTolerations: []
nodeServerAffinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: beta.kubernetes.io/instance-type
              operator: NotIn
              values:
                - BBC
            - key: beta.kubernetes.io/instance-gpu
              operator: NotIn
              values:
                - "true"

controllerServerTolerations: []
controllerServerAffinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - csi-cdsplugin-controller-server
          topologyKey: "kubernetes.io/hostname"