apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cds-hp1
parameters:
  paymentTiming: Postpaid
  reservationLength: "3"
  storageType: hp1
provisioner: cds.csi.baidubce.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer